spring.application.name=movie-management
spring.datasource.url=jdbc:postgresql://localhost:5432/mm26
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update